"""Generate `docs/setup/sources.md` from the data-source registry.

    python -m core.scripts.ops.gen_setup_docs           # (re)write the doc
    python -m core.scripts.ops.gen_setup_docs --check   # exit 1 if it is stale (CI gate)
    python -m core.scripts.ops.gen_setup_docs --print   # write nothing, print to stdout

The published table of "where our data comes from" is generated for the same reason the
code map is: a hand-maintained provenance list is wrong within a month, and a provenance
list nobody trusts is worse than none. `core.backend.sources` is the single source of
truth — it also drives what `bootstrap` actually ingests — so this document cannot claim a
source the build doesn't use, or miss one it does.

Don't edit the output. Change the registry and re-run.
"""
from __future__ import annotations

import argparse
import sys

from core.backend import sources
from core.config import PROJECT_ROOT

OUT = PROJECT_ROOT / "docs" / "setup" / "sources.md"

BANNER = (
    "<!-- GENERATED by `python -m core.scripts.ops.gen_setup_docs` — DO NOT EDIT.\n"
    "     Change core/backend/sources.py and re-run. -->"
)


def render() -> str:
    L: list[str] = [BANNER, "", "# Data sources", ""]
    L += [
        "Every dataset this project ingests, where it comes from, what it costs, and what",
        "it is allowed to be used for.",
        "",
        "This page is **generated from [`core/backend/sources.py`]"
        "(../../core/backend/sources.py)** — the same registry that drives what",
        "`bootstrap` actually downloads and what `update_all` refreshes. If a source is",
        "listed here, the build pulls it; if the build pulls it, it is listed here.",
        "",
        "```bash",
        "python -m core.scripts.setup.bootstrap --sources   # the same information, in the terminal",
        "```",
        "",
        "---",
        "",
        "## At a glance",
        "",
        "| Source | Licence | Auth | Datasets |",
        "|---|---|---|---|",
    ]
    for sid, src in sources.SOURCES.items():
        ds = [d for d in sources.DATASETS if d.source == sid]
        if not ds:
            continue
        auth = f"`{src.auth_env}`" if src.auth_env else "—"
        name = f"[{src.provider}]({src.url})" if src.url else src.provider
        L.append(f"| {name} | {src.licence} | {auth} | {len(ds)} |")
    L += [
        f"| **Total** | | | **{len(sources.DATASETS)}** |",
        "",
        "> A build reports progress from what the loaders say they have actually ingested,\n"
        "> never from a predicted size. A step is done when the script says it is done.",
        "",
    ]

    # ---- credentials -------------------------------------------------------
    L += ["## Credentials you need", "",
          "All of these live in `core/.env`, which is gitignored.", "",
          "| Variable | Unlocks | Where to get it |", "|---|---|---|"]
    where = {
        "NASDAQ_DATA_LINK_API_KEY": "https://data.nasdaq.com/account/profile",
        "FRED_API_KEY": "https://fredaccount.stlouisfed.org/apikeys",
        "SEC_USER_AGENT": "your own name + email, e.g. `Jane Doe jane@example.com`",
    }
    for env, providers in sources.required_env():
        w = where.get(env, "")
        w = f"<{w}>" if w.startswith("http") else w
        L.append(f"| `{env}` | {', '.join(providers)} | {w} |")
    L += ["",
          "Sources with no `Auth` entry above need no credential.", "", "---", ""]

    # ---- per source --------------------------------------------------------
    for sid, src in sources.SOURCES.items():
        ds = [d for d in sources.DATASETS if d.source == sid]
        if not ds:
            continue
        L += [f"## {src.provider}", ""]
        L.append(src.blurb)
        L += ["",
              f"- **Licence:** {src.licence}",
              f"- **Updates:** {src.cadence}"]
        if src.auth_env:
            L.append(f"- **Auth:** `{src.auth_env}` in `core/.env`")
        if src.url:
            L.append(f"- **Home:** <{src.url}>")
        if src.docs_url:
            L.append(f"- **Docs:** <{src.docs_url}>")
        if src.caveat:
            L += ["", f"> ⚠ {src.caveat}"]
        L += ["", "| Dataset | Pulled from | Writes | Mode |",
              "|---|---|---|---|"]
        for d in ds:
            ep = d.endpoint
            ep = f"[{ep.split('//')[-1][:44]}…]({ep})" if ep.startswith("http") else f"`{ep}`"
            tables = ", ".join(f"`{t}`" for t in d.tables) or "—"
            L.append(f"| {d.label} | {ep} | {tables} | {d.mode or '—'} |")
        L.append("")
        notes = [d for d in ds if d.note]
        if notes:
            for d in notes:
                L.append(f"- **{d.label}** — {d.note}")
            L.append("")
        L += ["---", ""]

    # ---- build order -------------------------------------------------------
    L += ["## Build order", "",
          "Phases run in this order, and the order is load-bearing.", ""]
    for phase, desc in sources.PHASES:
        ds = sources.by_phase(phase)
        if not ds:
            continue
        L.append(f"{len(L) and ''}**{phase}** — {desc} "
                 f"({len(ds)} step{'s' if len(ds) != 1 else ''})")
        L.append("")
    L += [
        "Two constraints in particular:",
        "",
        "- **`TICKERS` loads first.** It builds `permaticker_lookup`, which every other",
        "  table's `permaticker` stamping reads. Load it late and the rest stamp nothing.",
        "- **Derived tables rebuild last**, once every input is fresh. Rebuilding one",
        "  mid-ingest gives you a snapshot of half-updated data that looks perfectly valid.",
        "",
        "See [the checklist](README.md) to run a build, and",
        "[database.md](database.md) for the database on its own.",
        "",
    ]
    return "\n".join(L).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="Exit 1 if the committed doc differs from the registry.")
    ap.add_argument("--print", dest="to_stdout", action="store_true",
                    help="Print instead of writing.")
    args = ap.parse_args()

    doc = render()
    if args.to_stdout:
        print(doc)
        return 0
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != doc:
            print(f"{OUT.relative_to(OUT.parents[2])} is STALE — "
                  "run: python -m core.scripts.ops.gen_setup_docs")
            return 1
        print(f"{OUT.name} is up to date.")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(doc)
    print(f"Wrote {OUT} — {len(sources.DATASETS)} datasets, "
          f"{len(sources.SOURCES)} sources")
    return 0


if __name__ == "__main__":
    sys.exit(main())
